name: Tester

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1.3.0
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
    - name: Loggly
      run: "curl -H \"content-type:application/json\" -d '{ \"repository\" : \"${{ github.repository }}\", \"branch\" : \"${{ github.ref }}\" , \"sha\" : \"${{ github.sha }}\", \"actor\" : \"${{ github.actor }}\", \"status\" : \"${{ job.status }}\" }' ${{ secrets.loggly_url }}"
